# see `jm config -h` for details

# options
savedir = "."
overwrite = false
bulk = false
both = false

# targets of `jm patrol`
# patrol = [
#   { url = "https://shonenjumpplus.com/episode/13932016480028799982", title = "阿波連さんははかれない" },
#   { url = "https://shonenjumpplus.com/", search = true },
#   ...
# ]
patrol = [
    {url = "https://comic-ryu.jp/series/list/up/[1-]", search = true},
    {url = "https://asacomi.jp/series/list/up/[1-]", search = true},
    {url = "https://bibibi-comic.com/series/list/up/[1-]", search = true},
    {url = "https://bigcomics.jp/series/list/up/[1-]", search = true},
    {url = "https://championcross.jp/series/list/up/[1-]", search = true},
    {url = "https://comic-growl.com/series/list/up/[1-]", search = true},
    {url = "https://comic-room-base.com/series/list/up/[1-]", search = true},
    {url = "https://comic.j-nbooks.jp/series/list/up/[1-]", search = true},
    {url = "https://comicpash.jp/series/list/up/[1-]", search = true},
    {url = "https://comicride.jp/series/list/up/[1-]", search = true},
    {url = "https://comics.comici.jp/series/list/up/[1-]", search = true},
    {url = "https://comics.manga-bang.com/series/list/up/[1-]", search = true},
    {url = "https://comirela.com/series/list/up/[1-]", search = true},
    {url = "https://ebookstore.corkagency.com/series/list/up/[1-]", search = true},
    {url = "https://g-comi.jp/series/list/up/[1-]", search = true},
    {url = "https://hanayume.com/series/list/up/[1-]", search = true},
    {url = "https://hayacomic.jp/series/list/up/[1-]", search = true},
    {url = "https://heros-web.com/series/list/up/[1-]", search = true},
    {url = "https://kansai.mag-garden.co.jp/series/list/up/[1-]", search = true},
    {url = "https://kimicomi.com/series/list/up/[1-]", search = true},
    {url = "https://manga-zegra.com/series/list/up/[1-]", search = true},
    {url = "https://mangabu.jp/series/list/up/[1-]", search = true},
    {url = "https://mangalt.jp/series/list/up/[1-]", search = true},
    {url = "https://mangaspa.nikkan-spa.jp/series/list/up/[1-]", search = true},
    {url = "https://namicomic.jp/series/list/up/[1-]", search = true},
    {url = "https://piacomic.jp/series/list/up/[1-]", search = true},
    {url = "https://rimacomiplus.jp/series/list/up/[1-]", search = true},
    {url = "https://studio.booklista.co.jp/series/list/up/[1-]", search = true},
    {url = "https://takecomic.jp/series/list/up/[1-]", search = true},
    {url = "https://younganimal.com/series/list/up/[1-]", search = true},
    {url = "https://youngchampion.jp/series/list/up/[1-]", search = true},
    {url = "https://comic-action.com/series", search = true},
    {url = "https://comic-days.com/series", search = true},
    {url = "https://comic-earthstar.com/series", search = true},
    {url = "https://comic-gardo.com/series", search = true},
    {url = "https://comic-ogyaaa.com/", search = true},
    {url = "https://comic-seasons.com/", search = true},
    {url = "https://comic-trail.com/series", search = true},
    {url = "https://comic-y-ours.com/series", search = true},
    {url = "https://comic-zenon.com/series", search = true},
    {url = "https://comicborder.com/", search = true},
    {url = "https://feelweb.jp/", search = true},
    {url = "https://ichicomi.com/series", search = true},
    {url = "https://kuragebunch.com/series/friday", search = true},
    {url = "https://kuragebunch.com/series/oneshot", search = true},
    {url = "https://magcomi.com/series", search = true},
    {url = "https://mangatime-square.com/series", search = true},
    {url = "https://ourfeel.jp/", search = true},
    {url = "https://shonenjumpplus.com/series", search = true},
    {url = "https://tonarinoyj.jp/series", search = true},
    {url = "https://www.sunday-webry.com/series", search = true},
    {url = "https://piccoma.com/web/weekday/product/list?weekday=[0-6]", search = true},
    {url = "https://www.mangabox.me/", search = true},
    {url = "https://gaugau.futabanet.jp/list/works?page=[1-]", search = true},
    {url = "https://souffle.life/manga", search = true},
    {url = "https://nikkangecchan.jp/", search = true},
    {url = "https://comic-porta.com/series/", search = true},
    {url = "https://www.splush.jp/", search = true},
    {url = "https://comiciwate.jp/", search = true},
    {url = "http://www.manga-gai.net/", search = true},
    {url = "https://webcomic.ohtabooks.com/list/", search = true},
    {url = "https://nora.gakken.jp/comic/", search = true},
    {url = "https://comic-walker.com/search/content", search = true},
    {url = "https://www.comic-essay.com/comics/page/[1-]/", search = true},
    {url = "https://comic.mf-fleur.jp/lineup_magazine/", search = true},
    {url = "https://comic-boost.com/genre/", search = true},
    {url = "https://pocket.shonenmagazine.com/series", search = true},
    {url = "https://yanmaga.jp/comics", search = true},
    {url = "https://daysneo.com/", search = true},
    {url = "https://www.comicnettai.com/series", search = true},
    {url = "https://rookie.shonenjump.com/", search = true},
    {url = "https://pachikuri.jp/list_manga/", search = true},
    {url = "https://www.yawaspi.com/", search = true},
    {url = "https://flowercomics.jp/", search = true},
    {url = "https://www.ganganonline.com/rensai", search = true},
    {url = "https://www.ganganonline.com/finish", search = true},
    {url = "https://www.shinshokan.com/webwings/", search = true},
    {url = "https://shiori-on.com/product", search = true},
    {url = "https://to-corona-ex.com/comics", search = true},
    {url = "https://mavo.takekuma.jp/all-list.php", search = true},
    {url = "https://manga-park.com/", search = true},
    {url = "https://www.123hon.com/polca/web-comic/", search = true},
    {url = "https://www.123hon.com/nova/web-comic/", search = true},
    {url = "https://gorakuweb.com/series", search = true},
    {url = "https://comics.pie.co.jp/list/comicart/", search = true},
    {url = "https://vcomi.jp/", search = true},
    {url = "https://novema.jp/comic/serial/", search = true},
    {url = "https://www.berrys-cafe.jp/comic/serial/", search = true},
    {url = "https://www.no-ichigo.jp/comic/serial/", search = true},
    {url = "https://lezhin.jp/", search = true},
    {url = "https://manga-5.com/series?p=[1-]", search = true},
    {url = "https://kirapo.jp/", search = true},
    {url = "https://www.yomonga.com/titles/", search = true},
    {url = "https://crea.bunshun.jp/list/comic-essay", search = true},
    {url = "https://bloom.homesha.co.jp/webcomic/", search = true},
    {url = "https://firecross.jp/ebook/comics?sort=1&page=[1-]", search = true},
    {url = "https://shuro.world/manga/page/[1-]/", search = true},
    {url = "https://laza.mandarake.co.jp/", search = true},
    {url = "https://leedcafe.com/webcomicinfo/page/[1-]/", search = true},
    {url = "https://to-ti.in/product", search = true},
    {url = "https://www.alphapolis.co.jp/manga/official/search?category%5B0%5D=men&category%5B1%5D=women&page=[1-]", search = true},
    {url = "https://manga.nicovideo.jp/", search = true},
    {url = "https://manga-no.com/", search = true},
    {url = "https://creators.mechacomic.jp/new", search = true},
    {url = "https://fullpercent.net/comic/plist/manga?p=[1-]", search = true},
    {url = "https://ganma.jp/web/", search = true},
    {url = "https://manga.line.me/daily_list?week_day=[1-7]", search = true},
    {url = "https://sai-zen-sen.jp/comics/", search = true},
    {url = "https://sai-zen-sen.jp/comics/twi4/", search = true},
    {url = "https://sai-zen-sen.jp/special/4pages-comics/", search = true},
    {url = "https://sukupara.jp/plus/", search = true},
    {url = "https://omocoro.jp/comic/page/[1-]/", search = true},
    {url = "https://neetsha.jp/inside/main.php?magazine=1+2+3+6+8", search = true},
    {url = "https://michikusacomics.jp/product", search = true},
    {url = "https://note.com/carula/magazines", search = true},
    {url = "https://gakcomic.gakken.jp/comic/", search = true},
    {url = "https://www.cmoa.jp/", search = true},
]

# [site."foobar"]
# username = "XXXX"
# password = "XXXX"

# [site."example.com"]
# username = "XXXX"
# password = "XXXX"
